baseURL = "https://lasu.dev/blog/"
publishDir = "../blog"
cleanDestinationDir = true
title = "Blog"
timeZone = "Asia/Seoul"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableGitInfo = true
[params]
  author = "Lasu Shin"
  description = "Articles by Lasu Shin about productivity, technology, health, and digital habits."
[languages]
  [languages.en]
    weight = 1
    [languages.en.params]
      label = "English"

  [languages.ru]
    weight = 2
    [languages.ru.params]
      label = "Русский"


# IMPORTANT: publish into repo-root /blog


[permalinks]
  posts = "/:slug/"
